# This defines a predefined figure or path to travel and should be executed.
# The return success means the request is received correctly
uint8 YTURNLEFT = 0
uint8 YTURNRIGHT = 1
uint8 OVALLEFT = 2
uint8 OVALRIGHT = 3
uint8 path
---
bool success