# Configuration Settings for bigbot zed_F9P
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyGPS  
    frame_id: gps
    uart1:
      baudrate: 115200            # default 9600
    # TMODE3 Config
    tmode3: 1                   # Survey-In Mode
    sv_in:
      reset: True               # True: disables and re-enables survey-in (resets)
                                # False: Disables survey-in only if TMODE3 is
                                # disabled
      min_dur: 300              # Survey-In Minimum Duration [s]
      acc_lim: 3.0              # Survey-In Accuracy Limit [m]

    inf:
      all: true                   # Whether to display all INF messages in console
    gnss:
      glonass: true             # gnss added edward
      beidou: true
      qzss: true
    #rate: 10.0    # not really do anything (edha)
    #nav_rate: 1  # added edward 
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
